### ISSUE TITLE
Support for British English

### ISSUE THREAD

**Issue by KaitlynEthylia** [wixette/meowlang#10]
Hi, this language looks really interesting and useful, but at the moment I'm really struggling with it because I can't read any of the supported languages. If the British English "Miaow" could be supported that would help a lot :p

**Comment by wixette** [comment]
Per https://simple.wikipedia.org/wiki/Meow

> Different languages have different ways of spelling "meow." For example, English has been using the meow spelling since 1842 and before that, it used the miaow, miau, or meaw spellings.[2] Spanish and German still use the miau spelling while French uses the miaou spelling.[3]

Will support `miaow` as an alternative English token.
